### ISSUE TITLE
Add more info to hover

### ISSUE THREAD

**Issue by derekeder** [datamade/probation-resources-map#22]
On the hover, it currently only shows the address

<img width="248" alt="screen shot 2016-08-01 at 10 06 55 pm" src="https://cloud.githubusercontent.com/assets/919583/17315808/4926b642-5834-11e6-95f1-7e6784dfab90.png">

Change it to:

**Facility name**
Facility type(s)
Street address (city/state/zip not needed)

**Comment by reginafcompton** [comment]
Will add logic for facility type, when that information is available in spreadsheet.
