### ISSUE TITLE
look into Open Referral standard

### ISSUE THREAD

**Issue by derekeder** [datamade/probation-resources-map#46]
To help share the data behind this project, let's look into outputting it in a format compatible with [Open Referral](https://openreferral.org/)

Here's some resources from @greggish:
- Table of elements and definitions: https://github.com/codeforamerica/OpenReferral/blob/master/Human%20Services%20Data%20Specification%20%20v1.0.md#vocabulary
- Elements and definitions in a spreadsheet: https://docs.google.com/spreadsheets/d/1u3aj5scZ6qCaTLW7Z99QokiBOw8vcPlyGGxNde2K4oA/edit#gid=0
- a 'flat' version that might be useful: https://docs.google.com/spreadsheets/d/1sqHXoPHfAQZsEFYaemYq5reaf0TWtWz2pG1cK2wbn2s/edit#gid=1867626204
- an example of CSVs for loading into the Ohana API: https://docs.google.com/spreadsheets/d/1qkysLj5MAAvaysuac_9H0hOvTAb1aJEMhUVJAECmj2c/edit#gid=595985385

**Comment by fgregg** [comment]
Hrmm...

Is there any tooling around this? Validators?

It would be attractive if there some django models that we could use to
enter the data and then bake out.

**Comment by derekeder** [comment]
Great question. 

@greggish, do there exist any validators for Oepn Referral? if not, we'd be happy to talk about helping you build some.

**Comment by greggish** [comment]
One of our volunteers, @niveditc, built [a validator for an earlier version of HSDS](http://niveditc.github.io/open-referral-validation/), and i think she might be working on one for v1.0. 

We're about to start an upgrade cycle to v1.1, and it's also on our agenda for that. That said, @derekeder i'd be glad to talk more...

**Comment by derekeder** [comment]
Open Referral released a new flat-file version of their spec that we should look into: https://openreferral.org/introducing-the-humanitarian-service-data-model/

If we can find a good way to translate our spreadsheet, or at least export it in this format, it would be a good step to take

**Comment by greggish** [comment]
It's experimental and as-yet-untested, I'm sure you could offer suggestions for improvements. I believe [this is the actual spreadsheet template here.](https://drive.google.com/open?id=1sqHXoPHfAQZsEFYaemYq5reaf0TWtWz2pG1cK2wbn2s)

cc'ing @devinbalkind

**Comment by devinbalkind** [comment]
Yes the HSDM sheet on that sheet is where we go to.

What is interesting to you about the flat sheet? Is it the single-table-ness or just the general simplicity. If you just like the simplicity and don't need everything in one table then you should also check out AirTable.com because we could make this into a 3-5 table AirTable that could have the best of both worlds.

**Comment by reginafcompton** [comment]
@derekeder 

I am working on a way to make the PRM spreadsheet into OpenReferral-friendly data: https://github.com/datamade/probation-resources-open-referral

Soon, we'll want to just parse the Google doc itself....https://developers.google.com/sheets/api/quickstart/python
