### ISSUE TITLE
Spreadsheet TLC

### ISSUE THREAD

**Issue by reginafcompton** [datamade/probation-resources-map#77]
David Fischer will examine the spreadsheet and add more data to the current categories, but possibly also update or rename some of the columns. We discussed one possible distinction for facility type:

behavioral health VS. mental health ( VS. sexual health)

If the data changes, then some of the JS logic may need to change, too. 

@derekeder, let's remember to touch base with David in a couple weeks.

**Comment by jmcorrigan** [comment]
Would also let him know that many of the website/image URLs don't work

**Comment by reginafcompton** [comment]
New data added, per this pull request: https://github.com/datamade/probation-resources-map/pulls?q=is%3Apr+is%3Aclosed
