### ISSUE TITLE
Automation of LAT and LONG

### ISSUE THREAD

**Issue by reginafcompton** [datamade/probation-resources-map#81]
When someone adds a facility to the Google spreadsheet, the LAT and LONG need to be included. Let's find a way to automate this process.

@derekeder, you mentioned a resource that can help with this.

**Comment by derekeder** [comment]
This spreadsheet has a script added to it that geocodes the address info from one cell and populates the lat/long cells. We should use this: 

https://docs.google.com/spreadsheets/d/1PR-qGXx-HPfLzofyD9o5yzCTTQ4uzcTOz5K9xJP-V38/edit#gid=164271551

**Comment by reginafcompton** [comment]
I added this script to the main Google sheet. It works! 

https://github.com/jackdougherty/google-sheets-geocoder
