### ISSUE TITLE
Test the site on different browsers with different OS

### ISSUE THREAD

**Issue by reginafcompton** [datamade/probation-resources-map#82]
Check that the site functions properly on Windows and IE.

Sign-up for 30-minute free trial: https://www.browserstack.com/

We had some difficulty with Windows running Chrome, so start there!

**Comment by jmcorrigan** [comment]
I tested the available Windows desktop configurations. I noticed that in all of them, when you type in an address, the autofill defaults to locations in California. Not sure if that's just a problem with the API/browserstack.

Beyond that, the only other issues came from Internet Explorer.

**All good:**
Mozilla/Windows 10
Chrome/Windows 10
Mozilla/Windows 8.1
Chrome/Windows 8.1
Mozilla/Windows 8
Chrome/Windows 8
Mozilla/Windows 7
Chrome/Windows 7
Mozilla/Windows XP

**Not all good:**
Explorer/Windows 10
	Filters don't work
	No Modal URLs
Explorer/Windows 8.1
	Filters don't work
	No Modal URLs
Explorer/Windows 7
	Tabs stay highlighted even after leaving page
	Filters don't work
	No Modal URLs

**Not allowed to test:**
Explorer/Windows 8
Explorer/Windows XP

**Comment by reginafcompton** [comment]
Resolved....IE does not support "includes," which caused the filters to crash.
